### ISSUE TITLE
Bottle Stuck at 0.01L

### ISSUE THREAD

**Issue by hwn2020** [WulfMarius/Better-Water-Management#4] opened 2017-12-08 00:13 UTC
TLD v.1.15

I have been using this mod for basically 30 in game days and have not had this issue yet, so it may be hard to reproduce.

The bottle only drained down to 0.01L and could not drink the rest of the water.  It does not give you the drink button.  If you drop it and then view it, you are given the option to drink using spacebar, which it lets you do.  It then acts as if the bottle is fuller then the 0.5L as it let me drink 0.63L  

It will not let you refill the bottle as it thinks there is still 0.01L

![the long dark screenshot 2017 12 07 - 16 26 25 85](https://user-images.githubusercontent.com/33557014/33744551-f20c7bde-db6e-11e7-8adc-ab6b2923696b.png)
![the long dark screenshot 2017 12 07 - 16 26 18 21](https://user-images.githubusercontent.com/33557014/33744621-5b1100c8-db6f-11e7-8eac-964480296b22.png)
![the long dark screenshot 2017 12 07 - 16 57 24 15](https://user-images.githubusercontent.com/33557014/33745029-c2591b88-db71-11e7-932e-126adcebf6f7.png)
![the long dark screenshot 2017 12 07 - 16 57 09 97](https://user-images.githubusercontent.com/33557014/33745030-c272b0f2-db71-11e7-8c82-e3f04e2782c3.png)

**Comment by WulfMarius** [comment] 2017-12-09 17:44
Confirmed and I already understand what's happening there.
I'll get that fixed in the next release.

Thanks for reporting!

**Comment by WulfMarius** [comment] 2017-12-11 18:12
The drink option in the inventory will not remain available, until the bottle is considered empty by Better-Water-Managment.

The original used different limits for considering bottles empty, which I wasn't obvious before, because the bottles disappeared in inventory.

**Closed as completed by WulfMarius** 2017-12-11 18:12 UTC
